In [ ]:
import numpy as np

class DataAnalytics:

    def __init__(self):
        self.arr = None

    def create_array(self):

        print("Select the type of array to create")
        print("1. 1D Array")
        print("2. 2D Array")
        print("3. 3D Array")

        ch = int(input("Enter your choice: "))

        match ch:

            case 1:
                n = input("Enter elements separated by space: ")
                self.arr = np.array(n.split(), dtype=int)
                print(self.arr)

                print("Choose an operation")
                print("1. Indexing")
                print("2. Slicing")
                print("3. Go Back")

                ch = int(input("Enter choice: "))

                match ch:
                    case 1:
                        i = int(input("Enter index: "))
                        print(self.arr[i])

                    case 2:
                        st = int(input("Enter starting index: "))
                        en = int(input("Enter ending index: "))
                        step = int(input("Enter step: "))
                        print(self.arr[st:en:step])

                    case 3:
                        return

                    case _:
                        print("Invalid input")

            case 2:
                r = int(input("Enter number of rows: "))
                c = int(input("Enter number of columns: "))

                arr = []

                for i in range(r):
                    values = input("Enter values separated by space: ").split()
                    row = []
                    for j in values:
                        row.append(int(j))
                    arr.append(row)

                self.arr = np.array(arr)
                print(self.arr)

                print("Choose an operation")
                print("1. Indexing")
                print("2. Slicing")
                print("3. Go Back")

                ch = int(input("Enter choice: "))

                match ch:
                    case 1:
                        r = int(input("Enter row index: "))
                        c = int(input("Enter column index: "))
                        print(self.arr[r, c])

                    case 2:
                        rst = int(input("Row start index: "))
                        ren = int(input("Row end index: "))
                        rstep = int(input("Row step: "))

                        cst = int(input("Column start index: "))
                        cen = int(input("Column end index: "))
                        cstep = int(input("Column step: "))

                        print(self.arr[rst:ren+1:rstep, cst:cen+1:cstep])

                    case 3:
                        return

                    case _:
                        print("Invalid input")

            case 3:
                d = int(input("Enter number of layers: "))
                r = int(input("Enter number of rows: "))
                c = int(input("Enter number of columns: "))

                arr = []

                for i in range(d):
                    layer = []

                    for j in range(r):
                        values = input("Enter values separated by space: ").split()
                        row = []

                        for k in values:
                            row.append(int(k))

                        layer.append(row)

                    arr.append(layer)

                self.arr = np.array(arr)
                print(self.arr)

                print("Choose an operation")
                print("1. Indexing")
                print("2. Slicing")
                print("3. Go Back")

                ch = int(input("Enter choice: "))

                match ch:

                    case 1:
                        l = int(input("Enter layer index: "))
                        r = int(input("Enter row index: "))
                        c = int(input("Enter column index: "))

                        print(self.arr[l, r, c])

                    case 2:
                        ls = int(input("Layer start index: "))
                        le = int(input("Layer end index: "))
                        lstep = int(input("Layer step: "))

                        rs = int(input("Row start index: "))
                        re = int(input("Row end index: "))
                        rstep = int(input("Row step: "))

                        cs = int(input("Column start index: "))
                        ce = int(input("Column end index: "))
                        cstep = int(input("Column step: "))

                        print(self.arr[ls:le+1:lstep, rs:re+1:rstep, cs:ce+1:cstep])

                    case 3:
                        return

                    case _:
                        print("Invalid input")

    def math_op(self):

        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")

        ch = int(input("Enter your choice: "))

        data = input("Enter elements for second array: ").split()

        nums = []
        for i in data:
            nums.append(int(i))

        arr2 = np.array(nums).reshape(self.arr.shape)

        match ch:

            case 1:
                print(self.arr + arr2)

            case 2:
                print(self.arr - arr2)

            case 3:
                print(self.arr * arr2)

            case 4:
                print(self.arr / arr2)
    def combine_split(self):

        print("\nChoose an option:")
        print("1. Combine Arrays")
        print("2. Split Array")

        ch = int(input("Enter your choice: "))

        match ch:

            case 1:

                data = input("Enter elements of another array: ").split()

                nums = []
                for i in data:
                    nums.append(int(i))

                arr2 = np.array(nums).reshape(self.arr.shape)

                result = np.vstack((self.arr, arr2))

                print("\nCombined Array:")
                print(result)

            case 2:

                parts = int(input("Enter number of splits: "))
                result = np.array_split(self.arr, parts)

                print(result)

    def search_sort_filter(self):

        print("\nChoose an option:")
        print("1. Search a value")
        print("2. Sort the array")
        print("3. Filter values")

        ch = int(input("Enter your choice: "))

        match ch:

            case 1:

                val = int(input("Enter value to search: "))
                result = np.where(self.arr == val)

                print("Value found at index:", result)

            case 2:

                print("\nSorted Array:")
                print(np.sort(self.arr))

            case 3:

                val = int(input("Show values greater than: "))
                print(self.arr[self.arr > val])
        
    def statistics(self):

        print("\nChoose an aggregate/statistical operation:")
        print("1. Sum")
        print("2. Mean")
        print("3. Median")
        print("4. Standard Deviation")
        print("5. Variance")

        ch = int(input("Enter choice: "))

        match ch:

            case 1:
                print("Sum:", np.sum(self.arr))

            case 2:
                print("Mean:", np.mean(self.arr))

            case 3:
                print("Median:", np.median(self.arr))

            case 4:
                print("Standard Deviation:", np.std(self.arr))

            case 5:
                print("Variance:", np.var(self.arr))
obj = DataAnalytics()

print("Welcome to Python Analyzer!")
print("===========================")

while True:

    print("Choose an option:")
    print("1. Create a Numpy Array")
    print("2. Perform Mathematical Operations")
    print("3. Combine or Split Array")
    print("4. Search, Sort or Filter Arrays")
    print("5. Compute Aggregates and Statistics")
    print("6. Exit")

    ch = int(input("Enter your choice: "))

    match ch:
        case 1:
            obj.create_array()

        case 2:
            obj.math_op()

        case 3:
            obj.combine_split()

        case 4:
            obj.search_sort_filter()

        case 5:
            obj.statistics()

        case 6:
            break

        case _:
            print("Invalid Input")

Welcome to Python Analyzer!
Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Array
4. Search, Sort or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  1


Select the type of array to create
1. 1D Array
2. 2D Array
3. 3D Array


Enter your choice:  2
Enter number of rows:  2
Enter number of columns:  2
Enter values separated by space:  1 2 
Enter values separated by space:  3 4


[[1 2]
 [3 4]]
Choose an operation
1. Indexing
2. Slicing
3. Go Back


Enter choice:  1
Enter row index:  0
Enter column index:  1


2
Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Array
4. Search, Sort or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  2


1. Addition
2. Subtraction
3. Multiplication
4. Division


Enter your choice:  1
Enter elements for second array:  5 6 7 8


[[ 6  8]
 [10 12]]
Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Array
4. Search, Sort or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  3



Choose an option:
1. Combine Arrays
2. Split Array


Enter your choice:  1
Enter elements of another array:  4 5 6 7



Combined Array:
[[1 2]
 [3 4]
 [4 5]
 [6 7]]
Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Array
4. Search, Sort or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit
